# Netlify配置文件

[build]
  publish = "dist"
  command = "npm run build"

# 生产环境变量
[context.production.environment]
<<<<<<< HEAD
  VITE_API_URL = "https://96317f1de546.ngrok-free.app"

# 开发环境变量
[context.branch-deploy.environment]
  VITE_API_URL = "https://96317f1de546.ngrok-free.app"

# 部署预览环境变量
[context.deploy-preview.environment]
  VITE_API_URL = "https://96317f1de546.ngrok-free.app"
=======
  VITE_API_URL = "https://cac47729f298.ngrok-free.app"

# 开发环境变量
[context.branch-deploy.environment]
  VITE_API_URL = "https://cac47729f298.ngrok-free.app"

# 部署预览环境变量
[context.deploy-preview.environment]
  VITE_API_URL = "https://cac47729f298.ngrok-free.app"
>>>>>>> 070bbb46f778d0c39af61a47cf164aaab96eb240
